version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: never
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: 172.17.0.1
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wp_db
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress: