import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import Box from "@mui/material/Box";
import CssBaseline from "@mui/material/CssBaseline";
import Drawer from "@mui/material/Drawer";
import List from "@mui/material/List";
import Toolbar from "@mui/material/Toolbar";
import { ThemeProvider } from "@mui/material/styles";
import * as React from "react";
import theme from "../theme";
import { AdminAction } from "./components/AdminAction";
import { AdminBar } from "./components/AdminBar";
import { Divider } from "@mui/material";

export const metadata = {
  title: "Admin",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const drawerWidth = 240;

  return (
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <Box sx={{ display: "flex" }}>
              <CssBaseline />
              <AdminBar drawerWidth={drawerWidth} />
              <Drawer
                sx={{
                  width: drawerWidth,
                  flexShrink: 0,
                  "& .MuiDrawer-paper": {
                    width: drawerWidth,
                    boxSizing: "border-box",
                  },
                }}
                variant="permanent"
                anchor="left"
              >
                <List>
                  <AdminAction name="Aktualności" url="/admin/news" />
                  <AdminAction name="Media" url="/admin/media" />
                  <AdminAction name="Strony" url="/admin/pages" />
                  <AdminAction name="Grupy" url="/admin/groups" />
                  <Divider />
                  <AdminAction name="Użytkownicy" url="/admin/users" />
                  <AdminAction name="Ustawienia" url="/admin/settings" />
                </List>
              </Drawer>
              <Box
                component="main"
                sx={{ flexGrow: 1, bgcolor: "background.default", p: 3 }}
              >
                <Toolbar />
                {children}
              </Box>
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
  );
}
